FROM golang:1.20-alpine as builder

WORKDIR /app

COPY . .

RUN go mod download

RUN go build -o app

FROM golang:1.20-alpine

WORKDIR /app

COPY --from=builder /app/app .

EXPOSE 3000

CMD ["go", "run", "main.go"]
